### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by mwhit74** [mwhit74/moving_loads#1]
Need a user interface. Command line interface would be fine.

**Comment by eyaffe** [comment]
Hello, mwhit74. I have tried to implement something that I think might be useful. See: pull request.

**Comment by mwhit74** [comment]
Sorry just getting back to you. I pulled your code the other day and it is a big help. I tweaked the style, not your fault I don't have a style guide recommendation published, and fixed a small typo. I also integrated it directly with the rest of the code. It works very well.

Thanks for your help. :)
